### ISSUE TITLE
Images not rendered during conversion.

### ISSUE THREAD

**Issue by varunchauhan49** [alextiley/convert-html-to-pdf#13]
I have HTML content created using **mustache**. When converting to pdf the images are getting repaced with alt text.
 
```
   const rendered = mustache.to_html(content.toString(), options);

    const htmlToPDF = new HTMLToPDF(rendered);
    const pdf = await htmlToPDF.convert();
    
    return callback(null, pdf);
```

Help me understand how do I handle this case?

**Comment by alextiley** [comment]
@varunchauhan49 How are the images being loaded? Over HTTP or via base64 encoded images? Please see the readme for both use cases.
